[workspace]
members = [
    "wireguard-tools",
    "."
]

[package]
name = "wireguard-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
configparser = { version = "3.0.2" }

[features]
default = [

]
